### ISSUE TITLE
global weapon rebalancing

### ISSUE THREAD

**Issue by katelyynn** [katelyynn/laser-tag#2]
from my limited solo testing, the weapons are a bit unbalanced.

- the main crossbow has _slightly too slow_ timings
- the machine crossbow is _very_ overpowered, should probably limit the amount of available shots
- the rocket crossbow does not do nearly enough damage for how many rockets you actually get

**Comment by plexiondev** [comment]
this is planned once i can start doing proper playtesting (which should be soon)

**Comment by plexiondev** [comment]
from my recent limited multiplayer testing:
- crossbows do *so much* damage
  - the normal crossbow does more damage than the literal rocket crossbow
- should find a way to reduce the delay of machine crossbow to holding down
  - spam-clicking is pretty dumb
- rocket crossbows could allow for a "rocket jump"
  - detect arrow on ground then summon creeper? (disable `mobGriefing`)

**Comment by plexiondev** [comment]
could also decrease reload times a bit..? watching other shooters they're not nearly as long as present here.

**Comment by katelyynn** [comment]
oh yeah, this has been done this week
